
title: Hafize Güngör
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "https://hafizegungor.com/" # the subpath of your site, e.g. /blog
url: "https://hafizegungor.com/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hafize Güngör # add your name
author-img: hgm.png # add your photo
about-author: Computer & Software Engineer. # add description
social-github: gungorhafize # add your Github handle
social-linkedin: hafize güngör # add your Linkedin handle
social-medium: hafizegungor
social-email:  # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

google_adsense: ca-pub-3822577647724760

# Tracker
analytics: # Google Analytics

# Build Settings
 github: [metadata]
 encoding: UTF-8
 kramdown:
 input: GFM
 hard_wrap: false
 future: true
 jailed: false
 autoads: true
 theme: gungorhafize.github.io
 gfm_quirks: paragraph_end
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
